
project_id = "wugchjmppwehwlcflgor"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://preview--levi-a-pro.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.market-data-stream]
verify_jwt = false

[functions.news-aggregator]
verify_jwt = false

[functions.trading-signals-engine]
verify_jwt = false

[edge-runtime]
enabled = true
policy = "per_request"
inspector_port = 8083
