
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wugchjmppwehwlcflgor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Z2Noam1wcHdlaHdsY2ZsZ29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzgzNzUsImV4cCI6MjA2MDQxNDM3NX0.s1504dwjQmqN93cKMU681srHyNt1r1jO0FPtUtwMU-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
